/**
 * Namen bij de VBN-kenmerkcodes die Floriday als `vbnCode` meestuurt.
 *
 * Gegenereerd door scripts/haal-vbn-kenmerkcodes.mjs uit de publieke codelijsten van
 * Floricode - niet met de hand bijwerken, draai dat script opnieuw.
 *
 * Bron: https://www.floricode.com/Portals/0/Downloads/VBN%20codes/N-Kenmerkcodes%20snij_4.pdf
 *        https://www.floricode.com/Portals/0/Downloads/VBN%20codes/N-Kenmerkcodes%20pot_3.pdf
 * Opgehaald: 2026-08-04 (snijbloemen: 149, planten: 152)
 */
export const VBN_KENMERKCODES: Record<string, string> = {
  A01: "Potinhoud",
  A02: "Marketingconcept",
  A03: "Leeftijd",
  A04: "Uitgangsmateriaal",
  A13: "Nabehandeling",
  B15: "Logistiekekenmerken",
  I02: "Minplanthoogteincl.pot,ranges",
  I03: "Arrangementhoogte",
  I04: "Potmateriaalkweekpot",
  K03: "Bedrijfskenmerkfytosanitair",
  K04: "Certificatenaardwarmte",
  K05: "CertificatenMPS-TraceCert",
  K07: "Overigeleveranciersinformatie",
  K08: "CertificatenMPS-GA",
  K11: "FototoegevoegddoorRF",
  K13: "Productkwaliteitslabel",
  K15: "CertificatenSocialyQualified",
  K16: "CertificatenGLOBALG.A.",
  K17: "CertificatenMPSQuality",
  K18: "Certificatenbiologisch",
  K19: "Certificateneetbareproducten",
  K20: "CertificatenFlorimark",
  K21: "CertificatenMilieukeur",
  K22: "CertificatenKenyaFlowerCounsel",
  K23: "CertificatenFairtrade",
  K24: "KeurmerkMPS-ProductProof",
  K27: "CertificatenFlorverde",
  K28: "CertificatenEthicalTradeInitiat",
  K29: "CertificatenEthiopianEHPE",
  K30: "Certificatengewasbescherming",
  K31: "RainforestAlliance",
  K32: "CertificatenGRAS",
  K33: "LabelFairFlora",
  K34: "GLOBALG.A.P.ChainofCustody(CoC)",
  K35: "CertificatenVegaplan",
  K36: "CertificatenSIZASocial",
  K37: "GlobalG.A.P.ID",
  K38: "CertificaatSMET",
  K39: "CertificatenSIZAEnvironmental",
  K40: "CertificaatOHA",
  K41: "FlorEcuadorCertified",
  K42: "GLOBALG.A.PPlantPropagationMat.",
  K43: "GroenkeurBoomkwekerijproducten",
  K44: "MPS-GreenerGrown",
  K47: "USDANationalOrganicProgram",
  K48: "MPS-Compact",
  K49: "FloriCompact",
  K99: "FloricultureSustainabilityInitiat",
  L01: "Fust",
  L02: "Stapelwagen",
  L03: "Aantallegbordenveilingstapelwagen",
  L04: "AantallegbordenDeensestapelwagen",
  L05: "AantalonderstellenDeensestapelw.",
  L06: "Fustsoort",
  L07: "Fustmateriaal",
  L08: "AantallegbordenEurostapelwagen",
  L09: "AantalonderstellenEurostapelwagen",
  L11: "Aantal stelen per bos",
  L12: "Aantal bossen per bundel",
  L13: "Aantal stuks per fust",
  L14: "Aantal bossen per fust",
  L15: "Aantalbundelsperfust",
  L16: "Aantalbossenperhoes",
  L17: "Aantalbundelsperhoes",
  L18: "Fustlabel",
  L19: "Karlabel",
  L20: "Serviceproductlabel",
  L21: "Servicefustlabel",
  L22: "Servicekarlabel",
  L23: "Aantalfustenperlaag",
  L24: "Presentatieperschapm",
  L25: "Aantalfustenperladingdrager",
  S01: "Potmaat",
  S02: "Minimum planthoogte inclusief pot",
  S03: "Minaantalstekken/plantenperpot",
  S04: "Minimumplantdiameter",
  S05: "Rijpheidsstadium",
  S06: "Combinatiehoogte",
  S07: "Minaantalkoppenhoogstestam",
  S08: "Dikte",
  S09: "Minaantalbloemen/bloeiwijzenpot",
  S10: "Minaantalbloemtrossenperpot",
  S11: "Minimumaantaltakkenperplant",
  S12: "Minimumaantalbollenperpot",
  S13: "Minimumaantalbladerenperplant",
  S14: "Minimumstamhoogte",
  S15: "Transporthoogte",
  S16: "Lengtescheuten",
  S17: "Minaantvertakkingenprbloeiwijze",
  S18: "Maximumplanthoogteexclusiefpot",
  S19: "Minimumbloemknophoogte",
  S20: "Minimum steellengte",
  S21: "Gewicht (gemiddeld)",
  S22: "Minimumaantalbloemknoppensnijbl.",
  S23: "Minimum bloemdiameter",
  S24: "Minimumbloemschedelengte",
  S25: "Aantalbloemkoppenpertrekheester",
  S26: "Aant.kleuren/cultiv/vormenperkar",
  S27: "Aant.kleuren/cultiv/vormenperlaag",
  S28: "Aant.kleuren/cultiv/vormenperfust",
  S29: "Minimum bloeiwijzelengte",
  S30: "Verpakkingswijzesnijbloemen",
  S31: "Minimumaantbloemenperbol/steel",
  S32: "Minimumranklengte",
  S33: "Jaartalsorteringhout",
  S34: "Minimumbladdiameter",
  S35: "Minimum bundelgewicht",
  S36: "Maximumplanthoogteinclusiefpot",
  S37: "Maximumplantdiameter",
  S38: "Maxaantalbloemen/bloeiwijzenpot",
  S39: "Maximumaantaltakkenperplant",
  S40: "Maximumaantalbollenperpot",
  S41: "Maximumstamhoogte",
  S42: "Maximum steellengte",
  S43: "Maximumaantalknoppensnijbloemen",
  S44: "Maximumbloemdiameter",
  S45: "Maximumbloeiwijzelengte",
  S46: "Aantalvruchten/trossen",
  S47: "Verpakkingswijze",
  S48: "Minimumvruchtdiameter",
  S49: "Bolomvang",
  S50: "Bloem-, bes- of vruchtkleur",
  S51: "Potvorm",
  S52: "Potkleur",
  S53: "Potmateriaalompot",
  S54: "Plantvorm",
  S55: "Aantalkleuren/cultivperpot/bos",
  S56: "Teeltwijze",
  S57: "Teeltmedium",
  S58: "Hoesmateriaal",
  S59: "Hoesvorm",
  S60: "Hoesbedrukkingalgemeen",
  S61: "Extratoevoegingen",
  S62: "Land van herkomst",
  S64: "Hoesbedrukkingextra",
  S65: "Voorbehandeling",
  S66: "Overigenietinpot",
  S67: "Vormsnijbloemen",
  S68: "Buigzaamheidbloemsteel",
  S69: "Hoeskleur",
  S70: "Extradecomateriaal",
  S71: "Productkleur",
  S72: "Productmateriaal",
  S73: "Materiaalhoogte",
  S74: "Materiaaldiameter",
  S75: "Barcode",
  S76: "Productlabel",
  S77: "Eetbaar/nieteetbaar",
  S78: "Minimumplanthoogteexclusiefpot",
  S79: "Aantalkleuren/cultivpertray/fust",
  S80: "Maximumpercentageoudhout",
  S81: "Maximumlengteverschil",
  S82: "Bladkleur",
  S83: "Plantgewicht",
  S84: "Gemiddeldebloemdiameter",
  S85: "Bloem/bes/vruchtkleur",
  S86: "Winterhardheid(USDAzonesEuropa)",
  S87: "Kleurbehandeld",
  S88: "Bloem-/bladkleurverdeling",
  S89: "Minimumbloemknopdiameter",
  S90: "Volumeinhoud",
  S91: "Vruchtbenaming",
  S92: "Vaaslevenindex",
  S93: "Overigeinformatieplanten",
  S94: "Overigeinformatiesnijbloemen",
  S95: "Toepassingsmogelijkheid",
  S96: "Stamomtrek",
  S97: "CertificatenMPSABC",
  S98: "Kwaliteitsklasse",
  T01: "BTW-tarief",
  T02: "Prijseenheid",
  T03: "Transactievorm",
  T10: "Handelsverpakkingvoorwaarden",
  T11: "Consumentenverpakkingvoorwaarden",
  T12: "Leveringsvoorwaarden",
  T14: "Serviceheffingvoorwaarden",
  T15: "Algemenevoorwaarden",
  T16: "Marktvorm",
  T17: "Themadagen",
  T19: "Producentengroepen",
  T20: "FavorietenId",
  T21: "Verkoopeenheid",
  V11: "Restaantallen",
  V14: "RFH-milieucertificeringsstatus",
  V22: "PromotiekenmerkFloraHolland",
  V80: "ToegevoegdewaardesVR",
};

/** De naam bij een code, of de code zelf als die niet in de lijst staat. */
export function kenmerkNaam(code: string): string {
  return VBN_KENMERKCODES[code] ?? code;
}
